// GENERATED by scripts/bakeBeachSpinners.mts — do not edit by hand.
// Re-run `npm run bake:spinners` after any re-export of main 2.svg.
//
// The 20 beach spinners as baked rasters: their boxes in the beach's own viewBox units,
// plus the two encodings of each. BackgroundCanvas renders these instead of inlining the
// groups' markup — 4 230 DOM nodes and a whole-beach invisible measure pass removed.
import type { SpriteBox } from './utils/spriteBoxes'

export interface BakedSpinner {
  /** b2-prefixed Figma group id, as it appears in the prepared beach svg */
  id: string
  /** box in beach viewBox units, already padded by BOX_BLEED */
  box: SpriteBox
  /** master handed to next/image — never served at this size */
  src: string
  /** tiny copy for useAdaptiveText's cover */
  fill: string
  /** on-screen width as a share of the viewport, for next/image's `sizes` */
  sizes: string
}

/** sha256 of main 2.svg at bake time — verify:spinner-bake compares against the file. */
export const SPINNER_BAKE_SOURCE_HASH = '6fe5ffd82f7df8d9'

/** The beach art with the baked groups removed — what BackgroundCanvas fetches instead of
 *  main 2.svg. Fetching the full export would ship the spinners' markup as well as their
 *  rasters; see the note in the bake script. */
export const BEACH_BASE_SVG = '/SVG/background/main2-no-spinners.svg'

/** canvas units → raster pixels used when baking; see the SCALE note in the script. */
export const SPINNER_BAKE_SCALE = 3

/** The canvas the boxes are expressed in. Placement is a PERCENTAGE of this viewBox
 *  (boundedLayerStyle), so nothing here is in pixels and it survives resize, the
 *  cover-zoom and the phones-only scaleY untouched. */
export const SPINNER_BAKE_VIEWBOX = {"x":0,"y":0,"w":1027,"h":3614} as const

export const BAKED_SPINNERS: BakedSpinner[] = [
  {
    "id": "b2-type 1 palm 01",
    "box": {
      "x": -25.805845260620117,
      "y": 1576.9998779296875,
      "w": 220.68113708496094,
      "h": 233.000244140625
    },
    "src": "/PNG/background/spinners/type-1-palm-01.webp",
    "fill": "/PNG/background/spinners/type-1-palm-01-fill.webp",
    "sizes": "21.49vw"
  },
  {
    "id": "b2-type 1 palm 02",
    "box": {
      "x": 629.0859375,
      "y": 1713.0001220703125,
      "w": 242.78497314453125,
      "h": 256.0001220703125
    },
    "src": "/PNG/background/spinners/type-1-palm-02.webp",
    "fill": "/PNG/background/spinners/type-1-palm-02-fill.webp",
    "sizes": "23.64vw"
  },
  {
    "id": "b2-type 1 palm 03",
    "box": {
      "x": 217.79380798339844,
      "y": 1584.699951171875,
      "w": 150.5063018798828,
      "h": 146.5703125
    },
    "src": "/PNG/background/spinners/type-1-palm-03.webp",
    "fill": "/PNG/background/spinners/type-1-palm-03-fill.webp",
    "sizes": "14.65vw"
  },
  {
    "id": "b2-type 2 palm 01",
    "box": {
      "x": 239.4999237060547,
      "y": 1736.6845703125,
      "w": 129.3001251220703,
      "h": 128.82373046875
    },
    "src": "/PNG/background/spinners/type-2-palm-01.webp",
    "fill": "/PNG/background/spinners/type-2-palm-01-fill.webp",
    "sizes": "12.59vw"
  },
  {
    "id": "b2-type 2 palm 02",
    "box": {
      "x": 861.091796875,
      "y": 1745.1109619140625,
      "w": 149.728271484375,
      "h": 149.789306640625
    },
    "src": "/PNG/background/spinners/type-2-palm-02.webp",
    "fill": "/PNG/background/spinners/type-2-palm-02-fill.webp",
    "sizes": "14.58vw"
  },
  {
    "id": "b2-type 2 palm 03",
    "box": {
      "x": 383.1535339355469,
      "y": 1711.142578125,
      "w": 222.59652709960938,
      "h": 222.8577880859375
    },
    "src": "/PNG/background/spinners/type-2-palm-03.webp",
    "fill": "/PNG/background/spinners/type-2-palm-03-fill.webp",
    "sizes": "21.67vw"
  },
  {
    "id": "b2-type 2 palm 04 ",
    "box": {
      "x": 651.5000610351562,
      "y": 1545.6845703125,
      "w": 129.300048828125,
      "h": 128.82373046875
    },
    "src": "/PNG/background/spinners/type-2-palm-04.webp",
    "fill": "/PNG/background/spinners/type-2-palm-04-fill.webp",
    "sizes": "12.59vw"
  },
  {
    "id": "b2-type 3 palm 01",
    "box": {
      "x": 509.09979248046875,
      "y": 1607.1982421875,
      "w": 164.80010986328125,
      "h": 160.701171875
    },
    "src": "/PNG/background/spinners/type-3-palm-01.webp",
    "fill": "/PNG/background/spinners/type-3-palm-01-fill.webp",
    "sizes": "16.05vw"
  },
  {
    "id": "b2-type 3 palm 02",
    "box": {
      "x": 799.099853515625,
      "y": 1548.198974609375,
      "w": 216.7998046875,
      "h": 211.700927734375
    },
    "src": "/PNG/background/spinners/type-3-palm-02.webp",
    "fill": "/PNG/background/spinners/type-3-palm-02-fill.webp",
    "sizes": "21.11vw"
  },
  {
    "id": "b2-type 3 palm 03",
    "box": {
      "x": 20.099990844726562,
      "y": 1799.2001953125,
      "w": 222.00001525878906,
      "h": 215.60107421875
    },
    "src": "/PNG/background/spinners/type-3-palm-03.webp",
    "fill": "/PNG/background/spinners/type-3-palm-03-fill.webp",
    "sizes": "21.62vw"
  },
  {
    "id": "b2-type 3 palm 04",
    "box": {
      "x": 388.9986267089844,
      "y": 1583.886962890625,
      "w": 98.3013916015625,
      "h": 115.82421875
    },
    "src": "/PNG/background/spinners/type-3-palm-04.webp",
    "fill": "/PNG/background/spinners/type-3-palm-04-fill.webp",
    "sizes": "9.57vw"
  },
  {
    "id": "b2-type 2 umbrella 01",
    "box": {
      "x": 224.6999969482422,
      "y": 2117.60009765625,
      "w": 154.09999084472656,
      "h": 154.2998046875
    },
    "src": "/PNG/background/spinners/type-2-umbrella-01.webp",
    "fill": "/PNG/background/spinners/type-2-umbrella-01-fill.webp",
    "sizes": "15.00vw"
  },
  {
    "id": "b2-type 2 umbrella 02",
    "box": {
      "x": 365.6999206542969,
      "y": 2217.441650390625,
      "w": 233.90011596679688,
      "h": 234.258544921875
    },
    "src": "/PNG/background/spinners/type-2-umbrella-02.webp",
    "fill": "/PNG/background/spinners/type-2-umbrella-02-fill.webp",
    "sizes": "22.78vw"
  },
  {
    "id": "b2-type 2 umbrella 03",
    "box": {
      "x": 835.3273315429688,
      "y": 2295.39990234375,
      "w": 174.8726806640625,
      "h": 174.60009765625
    },
    "src": "/PNG/background/spinners/type-2-umbrella-03.webp",
    "fill": "/PNG/background/spinners/type-2-umbrella-03-fill.webp",
    "sizes": "17.03vw"
  },
  {
    "id": "b2-type 4 umbrella 01",
    "box": {
      "x": 774.099853515625,
      "y": 2103.60009765625,
      "w": 161.10009765625,
      "h": 161.50048828125
    },
    "src": "/PNG/background/spinners/type-4-umbrella-01.webp",
    "fill": "/PNG/background/spinners/type-4-umbrella-01-fill.webp",
    "sizes": "15.69vw"
  },
  {
    "id": "b2-type 4 umbrella 02",
    "box": {
      "x": 603.7999877929688,
      "y": 2403.2001953125,
      "w": 228.90008544921875,
      "h": 229.300048828125
    },
    "src": "/PNG/background/spinners/type-4-umbrella-02.webp",
    "fill": "/PNG/background/spinners/type-4-umbrella-02-fill.webp",
    "sizes": "22.29vw"
  },
  {
    "id": "b2-type 4 umbrella 03",
    "box": {
      "x": 13.000032424926758,
      "y": 2267.2998046875,
      "w": 210.49998474121094,
      "h": 211.10009765625
    },
    "src": "/PNG/background/spinners/type-4-umbrella-03.webp",
    "fill": "/PNG/background/spinners/type-4-umbrella-03-fill.webp",
    "sizes": "20.50vw"
  },
  {
    "id": "b2-type 3 umbrella 01",
    "box": {
      "x": 200.1999969482422,
      "y": 2447.300048828125,
      "w": 236.2000274658203,
      "h": 236.10009765625
    },
    "src": "/PNG/background/spinners/type-3-umbrella-01.webp",
    "fill": "/PNG/background/spinners/type-3-umbrella-01-fill.webp",
    "sizes": "23.00vw"
  },
  {
    "id": "b2-type 3 umbrella 02",
    "box": {
      "x": 29.299983978271484,
      "y": 2092.60009765625,
      "w": 165.70001220703125,
      "h": 165.60009765625
    },
    "src": "/PNG/background/spinners/type-3-umbrella-02.webp",
    "fill": "/PNG/background/spinners/type-3-umbrella-02-fill.webp",
    "sizes": "16.13vw"
  },
  {
    "id": "b2-type 3 umbrella 03",
    "box": {
      "x": 562.699951171875,
      "y": 2127.10009765625,
      "w": 123.300048828125,
      "h": 123.300048828125
    },
    "src": "/PNG/background/spinners/type-3-umbrella-03.webp",
    "fill": "/PNG/background/spinners/type-3-umbrella-03-fill.webp",
    "sizes": "12.01vw"
  }
]

/** by b2-prefixed id, for the render path */
export const BAKED_SPINNER_BY_ID = new Map(BAKED_SPINNERS.map(s => [s.id, s]))
