// GENERATED by scripts/bakeBgPosters.mts — do not edit; re-run `npm run bake:bg-posters`.
// Baked 2026-10-05 from http://127.0.0.1:3002/en. Each poster serves viewport widths [from, to).
export const BG_POSTERS: { from: number; to: number | null; w: number; h: number; src: string }[] = [
  {
    "from": 0,
    "to": 375,
    "w": 32,
    "h": 72,
    "src": "data:image/webp;base64,UklGRlIBAABXRUJQVlA4IEYBAADQCQCdASogAEgAPpk6mUgloyKhMBmcyLATCWoAtk2u/mfR6WYt3QN26QJo5lALgBjSl8ZatTKLNAiLdJLTzdH/g2a1C2DhaVD+qbA46SoS1cPFXCsT4kAA/q4Lv1cbTLlXG8ela8qRlpQ4JbnKV/STueo63VkQnH4IMi/yEHts3tL4ZFDjvoDrliH27ClUUGDWsg3UBcRf5j9+lTsnY7lGeNnSSlP+hLCXHcBAAOXn+leGpdCRjxarxvXA70w1sE14apsXGNjQ1pkqg3X2ULStks3OO6a1aRvNcbvyDq1FrW2GyjgKQ+qmzxrEySCXKhcb9zguwcCnXAYNjFvueLpI6cmy7R4zStzFmc3XLnabnnl19O35MMYjXgAl91LnDkfAuyPgcuVkVm8GK5cMQteT8veUc7UUXrR0c5Qrn2Wx7iVTZr8QAA=="
  },
  {
    "from": 375,
    "to": 410,
    "w": 32,
    "h": 72,
    "src": "data:image/webp;base64,UklGRlgBAABXRUJQVlA4IEwBAADwCQCdASogAEgAPpU2l0gloqIhMzqsALASiWoArlWN1T375geK33p7fbugdfrGKEpQz7ATdSYEz/tks6tUyk2kaW/I5gBw3ydYNwsofBB6QzIog5We0vrQAP6uGCp2m4hjPPxDnQ4T2GRjcNX8gx7BatNM3IR13Wp4PiZq0+p7OfePw0neHnF90GkR5rUxhiJF3IwDqDQZD0zC+0FSSdXmZINWuhtgQif9u62ntv2Sn2P4CZsJcK5zgDtn57oDxhxF/g3RRSeeLvhTpoFMUjts1X+l/e4Dojx0d8KQLGFoOBgt7LYuT3CWvW65hMkGZVpG2vpCiGnJqv0eCeg2IHH0HpIaALpvTvGCcu3f/ZLM5OcFU5V0V2PDLcMojl4okhWqeZfAvX524pJr7kmxg6POxmVlmwcr3GYEaMIVinblHVnFAVjpXY6+/OAAAA=="
  },
  {
    "from": 410,
    "to": 455,
    "w": 32,
    "h": 72,
    "src": "data:image/webp;base64,UklGRlwBAABXRUJQVlA4IFABAADQCgCdASogAEgAPpk+l0glo6IhLM1QsBMJbACnTUF+Z9GRcbyHHq2peY27oI3a1BZvAU/m5VXWRMmT4xm4DStc/pTY0hcm7QsORmjmMyHpIXCoBfF3NnCWVbNle5qcAAD+wtbSp0ZNMun8bxSbNNn93lTLczBPPfhptLJ2B+3CvXKVpHxSGrjp27ws2x52fNeRffmjLF4K8Fegn7N2buF4Efor1+A7Ff/TwxrAxGATOI+Mib2J69Jzly8JJVvnvcRE2/DERegnZRAdAKMgkcfXLY+5/bQQLWErG2/8qNC5efZQlzCmdgDYqY3cQd9W504RqnPnk0M+Umv/xm+FwsNkKVnQb5YVfu60CuctWbA4bh8k833kZ966ummdyQHw0IluZd6Y4bmSO/mbGAw43KDa4bPn0kp+YQkQCmCX1C6E0Lifvqc7DAfDtB9P0rcXQAA="
  },
  {
    "from": 455,
    "to": 520,
    "w": 32,
    "h": 72,
    "src": "data:image/webp;base64,UklGRlgBAABXRUJQVlA4IEwBAADwCQCdASogAEgAPp1ImkmlpKIhLNQKqLATiWoAtwEAOc8jxfcgtt7AO31pAamclbDZKp8b4MQCalY127Uz6ons7xdK1c6I+ApiLmrJHtnKdZVTt3ROR1AAAP6uHmt8dG33jG/xDngNOrzKA9uP8gx6GdjVKLySVlqPLgsbhGmYt/Nr2tvIvV2qnnBn+nuZnYHxtiIkd4PLiTXnsli6+yR/yWp0cd6etq99HPqKLPI4jQp8gm4voCDF7nBTmX4YooKlpcN/Wg+ubrAF5qbJnksgURpqKcsA4gXBqe8QvkRT0pAIuJEoFXcy8lwXNvmzydJUOmjhMHXERZAleAon2SdlTx7uWfmsqhbnpBnLO8VtlFrfHBZvGq/9uJ2GWJjBG0Rfs6sc/4DZ/B+IBiy3uD37iU8Hf9cm18i+ZrdTFM3q7G10MFHGqwBPiAAAAA=="
  },
  {
    "from": 520,
    "to": 600,
    "w": 32,
    "h": 63,
    "src": "data:image/webp;base64,UklGRiwBAABXRUJQVlA4ICABAADQCQCdASogAD8APpk6mEgloyIhMBv8ALATCWoAnTlBVZ5XfbuPi6L8htywNAaz6FITrIDEF641ZpD5RtWVsKlS1VIH2BS+b61OKZmS/VicdO9TCWOJdwAA/oqzeVSQ8xUnkgjv4IIJzYLYqS4mPyDFAv8dzDjewBuTPKeeSXgTmWvPd0VDP+/MDacG96crQir0ocaIe3Okyw5KiWxd28lnZBXwr33A2hrr14UMfz26pcok4DvKhZerymrbCchnYZGabavUf93LRvFkGaBzRbS1GifFEbZLR2mud+HSRdy+OSa0PypdKTI5X1LNujK9zaPdrEbUec8o2C1+oATIiMcNpC8ktypq4iucOP0NKlvWGytSBLrs2X9TVg5p4QugAAA="
  },
  {
    "from": 600,
    "to": 680,
    "w": 32,
    "h": 55,
    "src": "data:image/webp;base64,UklGRiQBAABXRUJQVlA4IBgBAABwCACdASogADcAPp1AmUklo6IhM/M4ALATiWgAnTNaP7+x8fvvVAuSAsl2mF35KQtz5rBoK2Ayvi1hROiTiJmbCe7koiItxUAg/1UAAP6Ks3cZg2IWToqBHnX+qYls/4cSq/+FaKx6BzKAb9w3JZAMEInztxjduG//fnmqxpHkz2AB24OFT260QVCc/X/45+OnxA5pKgaoef0zrquKytCe104Gso8+RzGDfYA8Lfdu40UqDYekQe5q9mMVle9frGgdBHmHgVSpFnIZa0ds0uWXCHyAcMHsFfmDhWKV1j0paHCAsir0z7IbzmtRNS53pqnbQ6nm+9Pr58i+f2Jrin9bwMp02LJ33eMTOFLoM+LkBYY9ZZFAAAAA"
  },
  {
    "from": 680,
    "to": 744,
    "w": 32,
    "h": 49,
    "src": "data:image/webp;base64,UklGRhIBAABXRUJQVlA4IAYBAABQCACdASogADEAPo04lEglI6IhM/zNUKARiWgAwrPMPKkC9FLb/Ag3ttfG6goCfLavd3/mutHRVQzn3sbjfTRq5eCSWjJZN2ULmWAA/lDTi2AdE5TxvEcav/q7lvpd5SY1/7jur/L2OiSTu8CYID3g/Zow2s6IuIpg1Cu7Ui9XUMgJcmc7d/Hwklbf3LLxkGWh8BB+/jTgiTO91EdZypWqm3b10/jYKvBg9mI7QiCKD4GskW81DkX6PV3t88Z43xWsVABoFrSo27dDNJU+wsp4bstwE2vLlw+DIlLYgR3ByCF7yJ73aHXcY7lK4gbw3tXaN1PEfumhHBelz/gqDfAN8pjefAAA"
  },
  {
    "from": 744,
    "to": 834,
    "w": 32,
    "h": 46,
    "src": "data:image/webp;base64,UklGRioBAABXRUJQVlA4IB4BAADQCACdASogAC4APp0+mUiloyIhNVQIALATiWwAnTlBVB34/VePufG7k3blH1AqId2l5sG87TP+ZQKlqBP2QjkL9PCLBeHb8iWv8CkeWSsAAP7gB/atPABqc6ZL8BviQ5JyEcDOOQUOK2eh6yFTQ0qdSdWVIbR87XZDxEbdtjbYbPg1oPUbeBdgE8GFty8b+PAeLHbA2VXPtyItTd6JfZyqUw51t8+bhvGa32xrwAlzF8coaGHQ4AJhV/s+vmXwEbqA3YLiT0eblRfGuPHSlIlqqGomDaUefVteubHArdaMiKNUj7JZprfhLkgdyqZPrhRf/pKcdLzDn75lLhyAsH0n0UcLlKIxOcEgQCMoFfJDwTecifM3KTNkwXY2YAAA"
  },
  {
    "from": 834,
    "to": 1024,
    "w": 32,
    "h": 46,
    "src": "data:image/webp;base64,UklGRhIBAABXRUJQVlA4IAYBAACQCACdASogAC4APo04lkglI6IhOrZoAKARiWwAnTlBU94N/Vbtu3vGa26X6qggrhudIy/vc8ByvRHiBsU+rLfdmjxSsPV5EbXIwMDHtAD+6vKpeJJw4tj8TiX2em/JuJdbR+Eiki3duvWQqaHY96Xql5xJdIgJUtVUin/uWETlOix6+U/+FcnVWYfTe1jDHHZNs+U2BkiBSvv7JPSgL2/0kN7Jnyup1nmVYtVBmua6wl/sOeU+8YCuF2tWeQz4aEkbGVYoUnDt77OC/yQppHf5agJp1Oj0QqUMDXTTLvcHvSiMexXZMysds7T099wG5K4aRJ+WwJa/nUr5kG0aFfkvZ2wHnQAA"
  },
  {
    "from": 1024,
    "to": 1600,
    "w": 48,
    "h": 48,
    "src": "data:image/webp;base64,UklGRloBAABXRUJQVlA4IE4BAACwCQCdASowADAAPoU4k0glI6GhON24AKAQiWwAnTKEgJ+ecm3zsZBwoNtldroGtxMf3vjruLy9w2R2ETGN8HkdAYzsygh0YjOPeVPCZgNIMh4z+smS4AD+kCbG3ppWOFGuYdaoUVuYlKyfGJay9EIHE/ZRKyrFib2IaiAeDmuLZu0EEW0J421t2mxiicgyGA7uk0QKjsW8yw+0LN33bUU/sQt106t3AFGFIqzThHbGkfgDy+vL+caid8tmROtS08LEfoAPOhes7QL0oLr2D3DOPJcuEriQdLxwGIb//D2z+TsmdvGdLXpFq899nQrjETIpdg1nKAK8yoytyJukqsgof4fQeAPcr7zqPq8pwWkTsnp6ULziwkobrABc6hKp5dk5fhNWR1Wy/+lURAITn8g7AqmYt7QAAga0Z0ehjyuj4/QvYLWZfozRIZWt20gA"
  },
  {
    "from": 1600,
    "to": 2240,
    "w": 48,
    "h": 35,
    "src": "data:image/webp;base64,UklGRjIBAABXRUJQVlA4ICYBAAAwCQCdASowACMAPpE8lUglo6IhNVqqqLASCWwArDmB133ofVeQIe7gX7Y8BjRZe+EcI8NyoUeS/CfMVYaHj04qv4jL8oYVrzAjCFApH7hXZb0AAP6QJFhwvCGcS5eWNB5OuASK+MvbssqgcJcIFEqmVqAgIM3fqYCU7kub+kF5Slpu29wBpIkJcjc0lQc9Zcivi4sZskvCMPGmPM0NyQcTr6uP7Jx4E2xxr5RNhFZTEoDsSs2YG6oPr94OmZqJZUCG0Q+crm7ESjebCxpleQeRocX/+jXfVzJREcqYKXak+Q2M91d4seqLkf64JhzP2oRLHbqoI42fCSHvjwYoBVXhH7VzZJC1Urj1hUCphiUIAng2xtQPdSzAJyqiPb5nRADCWMlwAAA="
  },
  {
    "from": 2240,
    "to": null,
    "w": 48,
    "h": 34,
    "src": "data:image/webp;base64,UklGRh4BAABXRUJQVlA4IBIBAAAQCACdASowACIAPok6lUglI6IhNVqtUKARCWoAnTKEhoE26pQGSdjH0gSDx6/RyU77CZDyOX9DsmiE4rtHZGHPGHhdBEi2gEHgAP6QIXl4AkUXbARHYdIMhJeQDtvhq/12UTP/60aS7X2KJ9jCnH/3Rz+wUGr033S5k11+3OguzF10dPQi46ul+z9R1QvTd41FuHl1sdskzhljmM3JfWGNcVJLSF0iecWPiVonUkHaWPDvj+AdYrfpd7ZjpCix1u6w9Dw92nD5rrzS3/P/TIW2eHZUVSDEeocOwBmt+99hLFX8dL6FSmX1GaJFjPHNyEDgp1YY99bzWLTNO3r5JltuCttT8H6/Tn38lkmN0fD/DQAA"
  }
]
