// Bakes the blurred background POSTERS — tiny stills of the settled scene that the page
// shows from the first paint, until the live BackgroundCanvas has assembled and fades in
// over them (see BgPoster.tsx).
//
// WHY. The live scene cannot appear early: it needs the 160 KB collage + the beach + a
// layout that converges over several passes (BackgroundCanvas, REVEAL_SETTLE_MS). On a slow
// phone (prod 2026-10-05, 1.6 Mbit, latency 150ms) the text paints at 0.8 s and the scene
// is ready at ~5–6 s — the first screen was bare sky for 4–5 seconds.
//
// WHY BLURRED, AND WHY SO MANY. The scene's framing is computed at runtime from the width
// (cover-zoom up to ×6 on phones, focal shift onto the statue, phones-only scaleY), so a
// SHARP still only lines up at the exact width it was shot at; anywhere else the cross-fade
// shows the statue twice. Heavy blur hides an offset of tens of px — but not more, and the
// framing moves fast below 1024: a 390-wide still on a 430 phone already puts the statue
// visibly higher and smaller. Mismatch was measured between neighbouring shots, blurred
// exactly as shipped (mean |Δ| per channel, 0–255): ≥1024 the scene merely scales (zoom 1)
// and neighbours differ by 2–4 → three posters cover 1024…∞; below it neighbours 30–80px
// apart already differ by 10–13 → one poster per step in SHOTS. Each is ~350 bytes of
// WebP, inlined as a data URI, so the whole set costs a few KB of HTML and zero requests.
//
// Viewport HEIGHT barely matters at the top of the scene (390×664 vs 390×932: zoom 545% vs
// 563%), so each shot is taken at a tall-ish height for its width — the extra art is what
// a tall phone shows; a shorter screen just crops it.
//
// One set serves all three locales, shot from /en. The cover-zoom does follow the page's
// height (ru text is longest: 390px zoom 575% vs en 561%), but measured the same way the
// locales differ by 4–5 — half the 10–13 between neighbouring width steps.
//
// Re-run after any change to the art, the cover-zoom/framing constants, or the hero layout
// (the statue is seated on the hero's top line). Needs a running build of the CURRENT code:
//   npm run build && npx next start -p 3002   # in another shell
//   npm run bake:bg-posters -- http://127.0.0.1:3002/en
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { chromium } from 'playwright'
import sharp from 'sharp'

const URL = process.argv[2] ?? 'http://127.0.0.1:3002/en'
const OUT = join('components', 'ui', 'background', 'bgPosters.ts')

// [shot width, shot height, poster pixel width]. Buckets switch at the midpoints between
// neighbouring shot widths — except at 1024 (WIDE_BREAKPOINT), where the framing itself
// jumps (cover-zoom ×2 → ×1), so the switch sits exactly there.
const SHOTS: [number, number, number][] = [
  [360, 810, 32], [390, 878, 32], [430, 968, 32], [480, 1080, 32], [560, 1100, 32],
  [640, 1100, 32], [720, 1100, 32], [768, 1100, 32], [900, 1300, 32],
  [1280, 1280, 48], [1920, 1400, 48], [2560, 1800, 48],
]
const SPLIT_AT: Record<number, number> = { 900: 1024 } // shot width → its bucket's end (excl.)
const BLUR_SIGMA = 1.2 // in POSTER pixels — ~15 css px on a phone, ~40 on a desktop

const browser = await chromium.launch()
const posters: { from: number; to: number | null; w: number; h: number; src: string }[] = []
for (let i = 0; i < SHOTS.length; i++) {
  const [w, h, pw] = SHOTS[i]
  const page = await browser.newPage({ viewport: { width: w, height: h } })
  await page.goto(URL, { waitUntil: 'load' })
  // The live scene has revealed (the same opacity the entrance gate drives)…
  await page.waitForFunction(() => {
    const el = document.querySelector('.background-canvas')
    return !!el && getComputedStyle(el).opacity === '1'
  }, null, { timeout: 60_000 })
  // …the content is hidden but keeps its layout (the cover-zoom reads <main>'s height), the
  // old poster is out of the shot, and the clouds have finished their staggered slide-in.
  await page.addStyleTag({
    content: 'main, body > div > div.fixed, [data-bg-poster] { visibility: hidden !important }',
  })
  await page.waitForTimeout(3500)
  const png = await page.screenshot()
  await page.close()
  const webp = await sharp(png).resize({ width: pw }).blur(BLUR_SIGMA).webp({ quality: 70 }).toBuffer()
  const meta = await sharp(webp).metadata()
  const prev = SHOTS[i - 1]?.[0]
  const next = SHOTS[i + 1]?.[0]
  const from = i === 0 ? 0 : (SPLIT_AT[prev!] ?? Math.round((prev! + w) / 2))
  const to = next == null ? null : (SPLIT_AT[w] ?? Math.round((w + next) / 2))
  posters.push({ from, to, w: meta.width!, h: meta.height!, src: `data:image/webp;base64,${webp.toString('base64')}` })
  console.log(`${w}x${h} → ${meta.width}x${meta.height}, ${webp.length} B, [${from}, ${to ?? '∞'})`)
}
await browser.close()

writeFileSync(OUT, `// GENERATED by scripts/bakeBgPosters.mts — do not edit; re-run \`npm run bake:bg-posters\`.
// Baked ${new Date().toISOString().slice(0, 10)} from ${URL}. Each poster serves viewport widths [from, to).
export const BG_POSTERS: { from: number; to: number | null; w: number; h: number; src: string }[] = ${JSON.stringify(posters, null, 2)}
`)
console.log(`wrote ${OUT}, ${posters.reduce((s, p) => s + p.src.length, 0)} chars of data URIs`)
