// The TOP CONTOUR of every Ocean Waves silhouette, as a polyline the foam clip follows.
//
// The type-2 foam rides behind a type-1 wave and is clipped to everything ABOVE that wave
// (beachWaves.ts → buildFoam). That clip used to be a straight line under the crest: in a
// trough the wave's edge is lower than the line, so the foam was cut off in mid-air before it
// ever reached the water. The clip now follows the wave's own outline, and this is where the
// outline comes from. Nothing in the browser can measure it cheaply — the silhouette is a
// stack of bands, its top edge is the union of a dozen curves — so it is measured here once,
// from a raster, and committed as data.
//
// Per file: rasterise at SCALE px per unit (Figma backdrop removed), and for every column
// find the first pixel whose alpha clears ALPHA_MIN. The polyline samples that edge at
// SAMPLES+1 evenly spaced x, and each sample takes the LOWEST edge inside its window. That is
// the safe side of the error: the foam is painted BEHIND its wave, so a clip line that sits a
// little inside the wave is hidden by the wave itself, while one that rides above the edge
// would cut the foam in the air — the very bug this replaces.
//
//   npm run gen:wave-crests
import sharp from 'sharp'
import fs from 'node:fs'

const DIR = 'public/SVG/background/Ocean Waves'
const OUT = 'components/ui/background/oceanWaveCrests.ts'
const IDS = ['01', '02', '03', '04', '05', '06'].map(n => `type 1 wave ${n}`)
const SCALE = 0.5
const SAMPLES = 128
const ALPHA_MIN = 128

const rows = []
for (const id of IDS) {
  const raw = fs.readFileSync(`${DIR}/${id}.svg`, 'utf8')
  const [, w, h] = raw.match(/viewBox="0 0 ([\d.]+) ([\d.]+)"/).map(Number)
  // Same backdrop strip as parseOceanWaveSvg — otherwise every column is opaque at y=0.
  const svg = raw.replace(/<rect\b[^>]*fill="#1E1E1E"[^>]*\/>/g, '')
  const W = Math.round(w * SCALE)
  const H = Math.round(h * SCALE)
  const { data } = await sharp(Buffer.from(svg), { density: 72 * SCALE })
    .resize(W, H, { fit: 'fill' })
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true })

  // First opaque row per column, in file units. A column with no ink at all is NaN and
  // skipped, not read as "edge at the bottom". The outermost pixel column on each side is
  // dropped too: the exports' top band stops a hair short of the frame while lower bands run
  // to it, so that column reads as a spike to the floor (wave 01: 510 against ~280 next to it).
  // The frame edges are ~700 units off-screen (WAVE_WIDTH_SCALE), the foam never gets there.
  const edge = new Float64Array(W)
  for (let x = 0; x < W; x++) {
    let y = 0
    while (y < H && data[(y * W + x) * 4 + 3] < ALPHA_MIN) y++
    edge[x] = y < H ? (y / H) * h : NaN
  }

  const ys = []
  for (let i = 0; i <= SAMPLES; i++) {
    const c = (i / SAMPLES) * W
    const lo = Math.max(1, Math.floor(c - W / SAMPLES / 2))
    const hi = Math.min(W - 2, Math.ceil(c + W / SAMPLES / 2))
    let low = -1
    for (let x = lo; x <= hi; x++) if (edge[x] > low) low = edge[x]
    if (low < 0) throw new Error(`${id}: no ink around x=${c / SCALE}`)
    ys.push(Math.round(low * 10) / 10)
  }
  const span = ys.reduce((a, b) => Math.max(a, b), 0) - ys.reduce((a, b) => Math.min(a, b), Infinity)
  console.log(`${id}: ${w}×${h}, crest y ${Math.min(...ys)}…${Math.max(...ys)} (span ${span.toFixed(0)})`)
  rows.push(`  '${id}': [${ys.join(', ')}],`)
}

fs.writeFileSync(OUT, `// GENERATED by scripts/genWaveCrests.mjs — do not edit by hand; re-run \`npm run gen:wave-crests\`
// after re-exporting public/SVG/background/Ocean Waves.
//
// Top contour of each wave silhouette in its OWN file units: ${SAMPLES + 1} y values at evenly spaced x
// from 0 to the file's width. Each value is the lowest edge within its sample window, so the
// polyline never rises above the art. Used by beachWaves.ts to clip the foam to the wave's
// outline instead of a straight line.
export const OCEAN_WAVE_CRESTS: Record<string, readonly number[]> = {
${rows.join('\n')}
}
`)
console.log(`wrote ${OUT}`)
