import type { CSSProperties } from 'react'

/**
 * The mobile burger's three bars, and the plant painted into each of them.
 *
 * The burger is a pill like every other in the header: a coloured ground with art
 * on top of it, clipped to the shape. It is only ever THREE grounds instead of one,
 * so the same plant is drawn three times, at three different offsets, and each copy
 * is clipped by the bar it belongs to. That is the whole design — Figma's Burger
 * (3468:45009) is three `Burger Line` frames, each holding a rounded rect and one
 * instance of the same component the "Туторы" pill wears on its left.
 *
 * Which is why nothing here is generated by `gen:pill-art`. A pill's decorations are
 * carved out of a hand-off sheet and re-seated on a bled window (see pillArt.ts);
 * these are the plain uncropped export, drawn at its own aspect and positioned by
 * CSS — the CoverPlants case, not the PillArt one. No window to bleed either: the
 * file holds the whole plant, so a hover that grows it only ever shows more of it.
 *
 * Every number is in px, straight off the Figma frames, and they are px rather than
 * ratios on purpose: the bars themselves are px in Header.tsx (`h-[12px] w-[40px]`,
 * spelled literally because Tailwind reads class names and cannot be handed a
 * constant), and the burger does not resize.
 */
export type BurgerLine = {
  /** the bar, matching the literal Tailwind size on its <span> in Header.tsx */
  w: number
  h: number
  /**
   * The plant's box inside that bar. `x`/`y` are its top-left corner — both mostly
   * negative, because the bar is a 12px window onto a plant ~100px tall and the
   * offset is what chooses which band of it shows. Height is left to the file's own
   * aspect (see burgerFlowerBox), so only the width is given.
   */
  art: { x: number; y: number; w: number }
}

/**
 * The plant itself: the "Туторы" pill's own left-hand export, RECOLOURED — the
 * burger wears the same flower in a muted mauve rather than the pill's magenta.
 *
 * A copy of the file, not the file: `Flower 2 - Tutors.svg` is what `gen:pill-art`
 * re-seats onto the Туторы pill, so recolouring it in place would repaint that pill
 * too. `Flower 2 - Burger.svg` is that file with its two `#CE59CC` fills replaced.
 * Everything else, the yellow heart included, is untouched — Figma's export of the
 * burger has it at the pill's own `#D9A63B`/`#E2C589`.
 *
 * The two fills are NOT the same colour, where the original's were, and that is the
 * whole subtlety. The petals are painted once solid and once again through a group at
 * `opacity .33, mix-blend-mode: multiply` — the veins. Multiplying a colour by itself
 * is what darkened the veins in the original, and in Figma's burger the veins are
 * LIGHTER than that relation gives, so a single swap cannot land both. So the solid
 * fill is the design's petal outright, and the multiply group carries the fill that
 * COMPOSITES to the design's vein:
 *
 *      petals  #8A5789                        → renders #8A5789   (Figma #8B588A)
 *      veins   #C17AC1 ×.33 multiply on those → renders #7F497E   (Figma #7F487E)
 *
 * which is why the second hex reads far too light to be a vein colour on its own.
 * The veins never leave the petals (nothing in the render composites this group over
 * the green), so the pair is exact rather than approximate.
 *
 * Both targets were measured off Figma's PNG export rather than read off a layer,
 * two ways that agree to one level: averaging Figma's pixels wherever this render
 * paints a flat tone (n≈7000), and k-means over the export's own flat purples.
 * Neither is a `--color-*` token — the palette in globals.css has no purple at all,
 * and this is the one place in the header that wants one.
 */
export const BURGER_FLOWER = '/SVG/header/decor/Flower 2 - Burger.svg'

/**
 * Top to bottom, matching the render order in Header.tsx.
 *
 * The middle bar is the wide one (48×18) and gets the plant SMALL and centred, so
 * its yellow heart lands in the middle of the bar; the outer two are narrow (40×12)
 * and get it large, cropped to a band of petals. Opening the menu hides the middle
 * bar and rotates the outer pair into the ✕ — the plants ride along inside them,
 * which is exactly what Figma's "Active" variant shows (its two bars carry the same
 * two offsets as `Defualt`'s first and third).
 *
 * `w` is Figma's own number for the instance. `x` and `y` are MEASURED, because
 * Figma's x for these instances is not the offset it looks like: it lands the plant
 * ~38.5 of the PLANT's own units too far right, which comes out as ~25px on the two
 * large copies and ~13.5px on the small one — proportional to the art, so it never
 * reads as one wrong number, and following it put a bare green wedge where the
 * design has petals.
 *
 * So each placement was fitted instead: render the plant into the bar's box at a
 * candidate offset, reduce both it and Figma's PNG export of that bar to a
 * plant-vs-ground mask, and take the offset with the fewest mismatched pixels.
 * All three land at 0.24–0.30% (8× supersampled), which is the antialiasing floor —
 * and the y that fit returns agrees with Figma's to an eighth of a pixel, which is
 * what says the discrepancy is real and confined to x.
 */
export const BURGER_LINES: readonly BurgerLine[] = [
  { w: 40, h: 12, art: { x: -29.75, y: -21.875, w: 109.6 } },
  { w: 48, h: 18, art: { x:  -4.125, y: -15.75, w:  59.11 } },
  { w: 40, h: 12, art: { x: -15.875, y: -68.75, w: 109.6 } },
]

/**
 * A plant's box inside its bar.
 *
 * `height: auto` is the same trick `plantBox` uses: an <img> is a replaced element,
 * so a width with no height takes the file's own aspect ratio and the art can never
 * be squashed. `maxWidth: 'none'` because Tailwind's preflight puts `max-width: 100%`
 * on every <img> and a max-width beats a width — the plant is 2.7× its bar wide, so
 * without it every copy would be clamped to the bar and drawn at the wrong scale
 * (see the note in pillArt.ts, which is where that bug was found the first time).
 *
 * Positioned with `left`/`top` rather than a transform: the hover writes the `scale`
 * property, and a transform on the same element would be scaled by it — the plant
 * would drift sideways as it grew.
 */
export function burgerFlowerBox(line: BurgerLine): CSSProperties {
  return {
    position: 'absolute',
    left:     line.art.x,
    top:      line.art.y,
    width:    line.art.w,
    height:   'auto',
    maxWidth: 'none',
  }
}
